# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IPlugIn
                                 A QGIS plugin
 Plugin to perform interpolation task for onfarm research module
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-22
        copyright            : (C) 2025 by Lucas Johannsen
        email                : lucas.johannsen@fh-kiel.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IPlugIn class from file IPlugIn.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .i_plugin import IPlugIn
    return IPlugIn(iface)
