# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OFEPlanning
                                 A QGIS plugin to plan On-farm experiments
 Planung von OFR-Versuchen
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-04
        copyright            : (C) 2026 by Christoph Ratke
        email                : christoph.ratke@agdoit.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OFRPlanning class from file OFRPlanning.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ofe_planning import OFEPlanning
    return OFEPlanning(iface)
