# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Enum versuchstypen
                                 A QGIS plugin to plan on-farm experiments
 Planung von OFE-Versuchen
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Christoph Ratke
        email                : christoph.ratke@agdoit.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from enum import Enum


class Versuchstyp(Enum):
    STREIFEN = 1
    KLEINPARZELLE = 2


class MapToolMode(Enum):
    NONE = 0
    AB_LINE = 1