# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OFEPlanning
                                 A QGIS plugin
 Planung von OFE-Versuchen
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-01-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Christoph Ratke
        email                : christoph.ratke@agdoit.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import logging
import os.path

from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.core import QgsProject, QgsMessageLog, Qgis

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ofe_planning_dialog import OFEPlanningDialog
from .constants import WORKING_DIR_NAME

logger = logging.getLogger(__name__)


class OFEPlanning:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # Configure logging
        self._setup_logging()

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'Praxisversuche')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def _setup_logging(self):
        """Configure logging for the plugin with console and QGIS message log."""
        plugin_logger = logging.getLogger('ofe_planning')
        if not plugin_logger.handlers:
            plugin_logger.setLevel(logging.DEBUG)
            handler = logging.StreamHandler()
            handler.setFormatter(logging.Formatter(
                '%(name)s - %(levelname)s - %(message)s'
            ))
            plugin_logger.addHandler(handler)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('OFEPlanning', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ofr_planning/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'OFE Planung'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)
        self.actions.clear()

        if hasattr(self, 'dlg') and self.dlg is not None:
            try:
                self.dlg._cleanup_layers()
            except Exception:
                pass
            self.dlg.close()
            self.dlg = None


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started

        # Check if the QGIS project is saved
        project_path = QgsProject.instance().fileName()
        if not project_path:
            QMessageBox.critical(
                None,
                self.tr("Fehler"),
                self.tr("Das QGIS-Projekt muss vor der Verwendung dieses Plugins gespeichert werden."),
            )
            return
        # Determine project directory
        project_dir = os.path.dirname(project_path)

        self.ofr_planung_dir = os.path.join(project_dir, WORKING_DIR_NAME)

        if not os.path.exists(self.ofr_planung_dir):
            os.makedirs(self.ofr_planung_dir)
            logger.info("Created working directory: %s", self.ofr_planung_dir)
        if self.first_start == True:
            self.first_start = False
            self.dlg = OFEPlanningDialog(self.ofr_planung_dir, self)

        if not self.dlg.map_initialized:
            self.dlg.initialize_map()
            self.dlg.load_saved_params()

        self.dlg.show()
        self.dlg.exec_()