# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OFEPlanningDialog
                                 A QGIS plugin to plan on-farm experiments
 Planung von OFE-Versuchen
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Christoph Ratke
        email                : christoph.ratke@agdoit.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import json
import logging
import math
import os
import random

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import (
    QgsApplication,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsFeature,
    QgsField,
    QgsGeometry,
    QgsLayoutExporter,
    QgsLayoutItemLabel,
    QgsLayoutItemLegend,
    QgsLayoutItemMap,
    QgsLayoutItemPicture,
    QgsLayoutItemScaleBar,
    QgsLayoutPoint,
    QgsLayoutSize,
    QgsLineString,
    QgsPointXY,
    QgsPolygon,
    QgsPrintLayout,
    QgsProcessingContext,
    QgsProcessingFeedback,
    QgsProject,
    QgsLayerTreeLayer,
    QgsRasterLayer,
    QgsRectangle,
    QgsUnitTypes,
    QgsVectorLayer,
)

from qgis.core import QgsMapLayerProxyModel
from qgis.gui import (
    QgsMapCanvas,
    QgsMapToolPan,
)

from qgis.PyQt.QtWidgets import QVBoxLayout, QMessageBox
from PyQt5.QtCore import Qt, QMetaType
from PyQt5.QtGui import QFont
import processing

from .ofe_planning_maptool import OfePlanningMapTool
from .generate_blocks import generate_blocks, BlockConfig
from .enum_versuchstypen import Versuchstyp
from .constants import (
    EPSG_WGS84,
    EPSG_UTM32N,
    DEFAULT_LAT,
    DEFAULT_LON,
    DEFAULT_MAP_EXTENT_PADDING,
    LAYER_GROUP_NAME,
    HEADLAND_BUFFER_SEGMENTS,
    FIELD_EXTENT_PADDING_FRACTION,
    VARIANT_COLORS,
    OSM_URL_PARAMS,
    OSM_LAYER_NAME,
    OSM_PROVIDER,
)
from .layer_manager import (
    is_layer_valid,
    is_valid_polygon_layer,
    is_valid_line_layer,
    get_layer_group,
    clean_layer_add,
    remove_layer,
    export_shapefile,
    export_layers_to_zip,
)
from .crs_utils import detect_utm_crs, reproject_layer
from .styling import (
    create_field_symbol,
    create_headland_inner_symbol,
    create_headland_pattern_symbol,
    create_ab_line_symbol,
    create_block_symbol,
    create_obstacle_symbol,
    apply_categorized_variant_renderer,
)
from .generate_core_plots import generate_core_plots

logger = logging.getLogger(__name__)

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ofe_planning_dialog_base.ui'))


class OFEPlanningDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, ofe_planungstool_dir, plugin_instance, parent=None):
        """Constructor."""
        super(OFEPlanningDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect

        self.setupUi(self)

        # Restrict combos to the appropriate geometry type
        for _cmb in [
            self.mapLayerComboBox_Feldgrenze,
            self.mapLayerComboBox_Feldgrenze_t3,
            self.cmb_feldgrenze_t5,
            self.mapLayerComboBox_AF,
            self.mapLayerComboBox_AF_t3,
            self.cmb_headland_t5,
            self.cmb_inner_t5,
            self.cmb_af_t5,
            self.cmb_plots_t5,
            self.cmb_core_t5,
            self.cmb_feldgrenze_t4,
            self.cmb_inner_t4,
            self.cmb_af_t4,
            self.cmb_plots_t4,
        ]:
            _cmb.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        for _cmb in [
            self.mapLayerComboBox_Lenkspur,
            self.mapLayerComboBox_Lenkspur_t3,
            self.cmb_guidance_t5,
        ]:
            _cmb.setFilters(QgsMapLayerProxyModel.LineLayer)

        self.ofe_planungstool_dir = ofe_planungstool_dir  # Path to working directory
        self.plugin_instance = plugin_instance  # Reference to plugin instance
        self.project = QgsProject.instance()
        self.tree_root = self.project.layerTreeRoot()
        self.setWindowFlags(Qt.WindowMinimizeButtonHint | Qt.WindowCloseButtonHint)
        self.init_settings()
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget.setTabEnabled(1, False)
        self.tabWidget.setTabEnabled(2, False)
        self.tabWidget.setTabEnabled(3, False)


        # Tab 1 connections
        self.int_faktoren.valueChanged.connect(self.on_faktoren_changed)
        self.btn_plan_ofe.clicked.connect(self.on_next_button_clicked)
        self.btn_plan_smallplot.clicked.connect(self.on_kleinparzellen_button_clicked)
        self.btn_exit.clicked.connect(self.cancel_button_clicked)

                
        # Tab 2 connections
        self.btn_feldgrenze_laden.clicked.connect(self.feldgrenze_laden)
        self.btn_lenkspuren_laden.clicked.connect(self.lenkspur_laden)
        self.btn_af_laden.clicked.connect(self.af_laden)
        self.btn_linieziehen.clicked.connect(self.btn_linieziehen_clicked)
        self.btn_randomisieren.clicked.connect(self.btn_randomisieren_clicked)
        self.btn_parzellenloeschen.clicked.connect(self.btn_parzellenloeschen_clicked)
        self.btn_parzellenanlegen.clicked.connect(self.on_btn_parzellenanlegen_clicked_alt)
        self.checkbox_vorgewende.stateChanged.connect(self.on_checkbox_vorgewende_toggle)
        self.num_vorgewende.valueChanged.connect(self.on_num_vorgewende_valueChanged)
        self.btn_exit_t2.clicked.connect(self.cancel_button_clicked)
        self.btn_back_t2.clicked.connect(self.button_back_clicked)
        self.btn_save_t2.clicked.connect(self.on_speicher_button_clicked)
        
        # Tab 3 connections
        self.btn_feldgrenze_laden_t3.clicked.connect(self.feldgrenze_laden)
        self.btn_lenkspuren_laden_t3.clicked.connect(self.lenkspur_laden)
        self.btn_af_laden_t3.clicked.connect(self.af_laden)
        self.btn_linieziehen_t3.clicked.connect(self.btn_linieziehen_clicked)
        self.btn_randomisieren_t3.clicked.connect(self.btn_randomisieren_clicked)
        self.btn_parzellenloeschen_t3.clicked.connect(self.btn_parzellenloeschen_clicked)
        self.btn_parzellenanlegen_t3.clicked.connect(self.on_btn_parzellenanlegen_clicked_alt)
        self.checkbox_vorgewende_t3.stateChanged.connect(self.on_checkbox_vorgewende_toggle)
        self.num_vorgewende_t3.valueChanged.connect(self.on_num_vorgewende_valueChanged)
        self.btn_exit_t3.clicked.connect(self.cancel_button_clicked)
        self.btn_back_t3.clicked.connect(self.button_back_clicked)
        self.btn_save_t3.clicked.connect(self.on_speicher_button_clicked)

        # Tab 4 connections
        self.btn_back_t4.clicked.connect(self.button_back_t4_clicked)
        self.btn_create_core_t4.clicked.connect(self.btn_create_core_t4_clicked)
        self.btn_load_json_t4.clicked.connect(self.btn_load_json_t4_clicked)
        self.btn_next_t4.clicked.connect(self.btn_next_t4_clicked)
        self.btn_save_t4.clicked.connect(self.btn_save_t4_clicked)

        # Tab 5 connections
        self.btn_browse_export_t5.clicked.connect(self._browse_export_t5)
        self.btn_export_t5.clicked.connect(self._export_t5)
        for _combo in [
            self.cmb_feldgrenze_t5, self.cmb_headland_t5, self.cmb_inner_t5,
            self.cmb_af_t5, self.cmb_plots_t5, self.cmb_core_t5, self.cmb_guidance_t5,
        ]:
            _combo.layerChanged.connect(self._update_t5_canvas)
        self.cmb_print_format_t5.currentIndexChanged.connect(self._update_print_button_state)
        self.txt_print_path_t5.textChanged.connect(self._update_print_button_state)
        self.btn_browse_print_t5.clicked.connect(self._browse_print_t5)
        self.btn_print_t5.clicked.connect(self._print_t5)
        self.btn_finish_t5.clicked.connect(self.btn_finish_t5_clicked)

        self.tabWidget.currentChanged.connect(self._on_tab_changed)

        # TODO: implement plotting, clean up
        # self.btn_parzellenanlegen.clicked.connect(self.parzellenanlegen_clicked)


        # self.versuchsparameter = {}
        self.versuchstyp=Versuchstyp.STREIFEN
        self.group_name = LAYER_GROUP_NAME
        self.feld_layer = None
        self.lenkspur_layer = None
        self.af_layer = None
        self.innerLayer = None
        self.bufferLayer = None
        self.ab_line_layer = None
        self.plot_layer = None
        self.block_layers = []
        self.core_plot_layers = []
        self.osm_layer = None
        self.map_initialized = False
        self.vorgewendebreite = 0.0
        self.ohne_vorgewende = False
        self.parzellenbreite = 0.0
        self.parzellenlaenge = 0.0
        self.wdh = 1
        self.gap_x = 0
        self.gap_y = 0
        self.anzahl_y = 1
        # Track last-applied layer IDs to skip redundant reloads
        self._applied_feld_id = None
        self._applied_lenkspur_id = None
        self._applied_af_id = None
        self.faktor1=""
        self.faktor2=""
        self.faktorstufen1 = []
        self.faktorenstufen2 = []
        self.anzahl_x = 0
        
        # Map components
        self.mapCanvas = QgsMapCanvas()
        self.maptool = OfePlanningMapTool(self.mapCanvas)
        self.target_crs = QgsCoordinateReferenceSystem(f"EPSG:{EPSG_UTM32N}")

        # TODO: check using signals for layer order 


    def on_faktoren_changed(self, value):
        """Enable or disable second factor inputs based on number of factors."""
        if value == 2:
            self.txt_faktor2.setEnabled(True)
            self.txt_faktorstufen2.setEnabled(True)
        else:
            self.txt_faktor2.setEnabled(False)
            self.txt_faktorstufen2.setEnabled(False)
            # Clear the fields when disabled
            self.txt_faktor2.clear()
            self.txt_faktorstufen2.clear()



    def on_txt_faktorstufen1_changed(self):
        faktorstufen1 = self.txt_faktorstufen1.text()
        faktorstufen1 = faktorstufen1.strip()
        stufen = faktorstufen1.split(',')
        if len(stufen) < 1:
            QMessageBox.warning(self, self.tr("Fehlende Eingabe"), self.tr("Bitte geben Sie die Faktorstufen als kommagetrennte Liste für Faktor 1 ein."))
            return False

        self.faktorstufen1 = []
        for stufe in stufen:
            self.faktorstufen1.append(stufe.strip())
        return True
            
    def button_back_clicked(self):
        # Move to first tab (Fragestellung)
        self.tabWidget.setTabEnabled(0, True)
        self.tabWidget.setTabEnabled(1, False)
        self.tabWidget.setTabEnabled(2, False)
        self.tabWidget.setCurrentIndex(0)

    def on_next_button_clicked(self):
        # Move to next tab (Smallplot)
        self.versuchstyp=Versuchstyp.STREIFEN
        self.tabWidget.setTabEnabled(1, True)
        self.tabWidget.setTabEnabled(2, False)
        self.tabWidget.setCurrentIndex(1)
        self.start_planning()

    def on_kleinparzellen_button_clicked(self):
        # Move to next tab (Kleinparzelle)
        self.versuchstyp = Versuchstyp.KLEINPARZELLE
        self.tabWidget.setTabEnabled(1, False)
        self.tabWidget.setTabEnabled(2, True)
        self.tabWidget.setCurrentIndex(2)
        self.start_planning()

    def _validate_planning_parameters(self):
        """Validate tab-1 inputs. Returns list of (widget, message) errors."""
        errors = []
        if not self.txt_fragestellung.toPlainText().strip():
            errors.append((self.txt_fragestellung, self.tr("Bitte geben Sie eine Versuchsfragestellung ein.")))
        if not self.txt_faktor1.text().strip():
            errors.append((self.txt_faktor1, self.tr("Bitte geben Sie den Namen für Faktor 1 ein.")))
        if not self.txt_faktorstufen1.text().strip():
            errors.append((self.txt_faktorstufen1, self.tr("Bitte geben Sie die Faktorstufen als kommagetrennte Liste für Faktor 1 ein.")))
        if self.int_faktoren.value() == 2:
            if not self.txt_faktor2.text().strip():
                errors.append((self.txt_faktor2, self.tr("Bitte geben Sie den Namen für Faktor 2 ein.")))
            if not self.txt_faktorstufen2.text().strip():
                errors.append((self.txt_faktorstufen2, self.tr("Bitte geben Sie die Faktorstufen für Faktor 2 ein.")))
        return errors

    def start_planning(self):
        """Validate inputs and move to next tab."""
        errors = self._validate_planning_parameters()
        if errors:
            widget, message = errors[0]
            QMessageBox.warning(self, self.tr("Fehlende Eingabe"), message)
            widget.setFocus()
            return

        # Initialize map when moving to second tab
        if not self.map_initialized:
            self.initialize_map()
            self.map_initialized = True

    def cancel_button_clicked(self):
        self.close()

    def reject(self):
        """Route ESC key through closeEvent like all other close paths."""
        self.close()

    def showEvent(self, event):
        """Re-sync the plugin canvas every time the dialog becomes visible."""
        super().showEvent(event)
        canvas_layers = self.get_canvas_layers()
        if canvas_layers:
            self.mapCanvas.setLayers(canvas_layers)
            self.mapCanvas.refresh()
            logger.debug("showEvent: canvas updated with %d layers: %s",
                         len(canvas_layers), [l.name() for l in canvas_layers])

    def closeEvent(self, event):
        """Intercept all close attempts (X button, ESC, cancel) and confirm with the user."""
        if not self.isVisible():
            event.accept()
            return

        reply = QMessageBox.question(
            self,
            self.tr("Planung beenden"),
            self.tr("Alle nicht gespeicherten Planungsdaten gehen verloren. Möchten Sie wirklich beenden?"),
            QMessageBox.Yes | QMessageBox.No,
            QMessageBox.No,
        )
        if reply != QMessageBox.Yes:
            event.ignore()
            return
        self._cleanup_layers()
        self._reset_state()
        event.accept()

    def _cleanup_layers(self):
        """Remove in-memory plugin layers; leave file-based (saved) layers in the project."""
        layers_to_remove = []
        tracked = [
            self.plot_layer, self.ab_line_layer, self.lenkspur_layer,
            self.af_layer, self.innerLayer, self.bufferLayer, self.feld_layer,
        ] + list(self.block_layers) + list(self.core_plot_layers)
        for layer in tracked:
            if is_layer_valid(layer) and layer.providerType() == "memory":
                layers_to_remove.append(layer.id())
        if layers_to_remove:
            QgsProject.instance().removeMapLayers(layers_to_remove)
        self.block_layers = []
        self.core_plot_layers = []

        # Only remove the group if it is now empty
        root = QgsProject.instance().layerTreeRoot()
        layer_group = root.findGroup(self.group_name)
        if layer_group and not layer_group.findLayers():
            root.removeChildNode(layer_group)

        if hasattr(self, 'maptool'):
            try:
                self.maptool.hide()
                self.mapCanvas.unsetMapTool(self.maptool)
            except Exception:
                pass

        self.mapCanvas.setLayers([])
        self.mapCanvas.refresh()

        if self.plugin_instance and self.plugin_instance.iface:
            self.plugin_instance.iface.mapCanvas().refresh()

    def _reset_state(self):
        """Reset all layer references and UI to initial state."""
        self.feld_layer = None
        self.lenkspur_layer = None
        self.af_layer = None
        self.innerLayer = None
        self.bufferLayer = None
        self.ab_line_layer = None
        self.plot_layer = None
        self.block_layers = []
        self.core_plot_layers = []
        self.osm_layer = None
        self.map_initialized = False

        # Reset Tab 1 form fields
        self.txt_fragestellung.clear()
        self.txt_faktor1.clear()
        self.txt_faktorstufen1.clear()
        self.txt_faktor2.clear()
        self.txt_faktorstufen2.clear()
        self.int_faktoren.setValue(1)
        self.on_faktoren_changed(1)

        # Reset Tab 2 layer combos
        self.mapLayerComboBox_Feldgrenze.setCurrentIndex(-1)
        self.mapLayerComboBox_Lenkspur.setCurrentIndex(-1)
        self.mapLayerComboBox_AF.setCurrentIndex(-1)

        # Reset Tab 3 layer combos
        self.mapLayerComboBox_Feldgrenze_t3.setCurrentIndex(-1)
        self.mapLayerComboBox_Lenkspur_t3.setCurrentIndex(-1)
        self.mapLayerComboBox_AF_t3.setCurrentIndex(-1)

        # Reset headland (Vorgewende) controls — block signals to prevent toggle_headland side effects
        _h_widgets = [
            self.checkbox_vorgewende, self.checkbox_vorgewende_t3,
            self.num_vorgewende, self.num_vorgewende_t3,
        ]
        for w in _h_widgets:
            w.blockSignals(True)
        self.checkbox_vorgewende.setChecked(False)
        self.num_vorgewende.setValue(0)
        self.checkbox_vorgewende_t3.setChecked(False)
        self.num_vorgewende_t3.setValue(0)
        for w in _h_widgets:
            w.blockSignals(False)
        self.ohne_vorgewende = False
        self.vorgewendebreite = 0.0
        self.buffer_is_active = False

        # Reset applied layer ID guards
        self._applied_feld_id = None
        self._applied_lenkspur_id = None
        self._applied_af_id = None

        # Refresh project/output directory in case project was saved
        self.init_settings()

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget.setTabEnabled(0, True)
        self.tabWidget.setTabEnabled(1, False)
        self.tabWidget.setTabEnabled(2, False)
        self.tabWidget.setTabEnabled(3, False)

    def initialize_map(self):
        """Initialize the map canvas with an OpenStreetMap background and zoom to a default coordinate."""
        self.mapCanvas.setCanvasColor(Qt.white)
        if self.mapWidget.layout() is None:
            self.layout_map = QVBoxLayout(self.mapWidget)
        else:
            self.layout_map = self.mapWidget.layout()
        self.layout_map.addWidget(self.mapCanvas)
                
        self.mapCanvas.setDestinationCrs(self.target_crs)
        
        self.pan_tool = QgsMapToolPan(self.mapCanvas)
        self.mapCanvas.setMapTool(self.pan_tool)
        
        self.osm_layer = QgsRasterLayer(OSM_URL_PARAMS, OSM_LAYER_NAME, OSM_PROVIDER)
        
        if self.osm_layer.isValid():
            self.background_layer = self.osm_layer
            self.mapCanvas.setLayers([self.background_layer])
        else:
            logger.warning("OpenStreetMap layer is not valid")

        # Default map center (WGS84)
        lat, lon = DEFAULT_LAT, DEFAULT_LON

        self.wgs84_crs = QgsCoordinateReferenceSystem(f"EPSG:{EPSG_WGS84}")
        transform_context = QgsProject.instance().transformContext()
        coordinate_transform = QgsCoordinateTransform(self.wgs84_crs, self.target_crs, transform_context)

        point_4326 = QgsPointXY(lon, lat)
        point_utm = coordinate_transform.transform(point_4326)
        
        padding = DEFAULT_MAP_EXTENT_PADDING
        self.mapCanvas.setExtent(QgsRectangle(
            point_utm.x() - padding, point_utm.y() - padding,
            point_utm.x() + padding, point_utm.y() + padding,
        ))
        self.mapCanvas.refresh()
        self.map_initialized = True

    def feldgrenze_laden(self):
        """Load the selected field boundary layer, detect its CRS, reproject to UTM, and add to the project."""
        if self.versuchstyp is Versuchstyp.KLEINPARZELLE:
            feldgrenze_layer = self.mapLayerComboBox_Feldgrenze_t3.currentLayer()
            btn = self.btn_feldgrenze_laden_t3
        else:
            feldgrenze_layer = self.mapLayerComboBox_Feldgrenze.currentLayer()
            btn = self.btn_feldgrenze_laden

        if not is_valid_polygon_layer(feldgrenze_layer):
            QMessageBox.critical(self, self.tr("Fehler"), self.tr("Ungültige Auswahl: Für 'Feldgrenze' muss ein Polygon-Vektorlayer ausgewählt werden."))
            self.mapLayerComboBox_Feldgrenze.setCurrentIndex(-1)
            return False

        if feldgrenze_layer.id() == self._applied_feld_id:
            return True

        btn.setEnabled(False)
        try:
            self.target_crs = detect_utm_crs(feldgrenze_layer.extent(), feldgrenze_layer.crs())
            self.feld_layer = self._load_or_reproject_field(feldgrenze_layer)
            if not self.feld_layer or not self.feld_layer.isValid():
                QMessageBox.critical(self, self.tr("Fehler"), self.tr("Der neue Layer konnte nicht geladen werden."))
                return False

            self.feld_layer.renderer().setSymbol(create_field_symbol())

            # Recreate layer group — null all child layer refs first so stale
            # C++ pointers don't survive the removeChildNode call
            self.innerLayer = None
            self.bufferLayer = None
            self.lenkspur_layer = None
            self.af_layer = None
            self.ab_line_layer = None
            self.plot_layer = None
            self._applied_lenkspur_id = None
            self._applied_af_id = None

            layer_group = self.tree_root.findGroup(self.group_name)
            if layer_group:
                self.tree_root.removeChildNode(layer_group)
            layer_group = self.tree_root.insertGroup(0, self.group_name)

            clean_layer_add(self.feld_layer)
            layer_group.addLayer(self.feld_layer)

            self.mapCanvas.setDestinationCrs(self.target_crs)
            self.mapCanvas.setLayers([self.feld_layer, self.osm_layer])
            self.mapCanvas.setExtent(self.feld_layer.extent())
            self.mapCanvas.refresh()
            self._applied_feld_id = feldgrenze_layer.id()

            # Re-apply headland if it was active
            if self.ohne_vorgewende:
                self.toggle_headland(True)

            return True
        finally:
            btn.setEnabled(True)

    def _load_or_reproject_field(self, feldgrenze_layer):
        """Reproject or load cached reprojected field boundary."""
        new_layer_name = "Feld_" + feldgrenze_layer.name()
        file_stem = f"Feld_{feldgrenze_layer.name()}_{feldgrenze_layer.id()}"
        os.makedirs(self.output_dir, exist_ok=True)
        output_path = os.path.join(self.output_dir, file_stem + ".shp")

        if os.path.exists(output_path):
            return QgsVectorLayer(output_path, new_layer_name, "ogr")

        params = {
            'INPUT': feldgrenze_layer,
            'TARGET_CRS': self.target_crs,
            'OUTPUT': output_path,
        }
        result = processing.run("native:reprojectlayer", params, feedback=QgsProcessingFeedback())
        return QgsVectorLayer(result['OUTPUT'], new_layer_name, "ogr")





    def lenkspur_laden(self):
        """Load the selected guidance line layer, reproject to UTM, and add to the project."""
        lenkspur_layer = self.mapLayerComboBox_Lenkspur.currentLayer()
        if not is_valid_line_layer(lenkspur_layer):
            QMessageBox.critical(self, self.tr("Fehler"), self.tr("Ungültige Auswahl: Für 'Lenkspur' muss ein Linien-Layer ausgewählt werden."))
            self.mapLayerComboBox_Lenkspur.setCurrentIndex(-1)
            return False

        if lenkspur_layer.id() == self._applied_lenkspur_id:
            return True

        self.btn_lenkspuren_laden.setEnabled(False)
        try:
            self.lenkspur_layer = reproject_layer(
                lenkspur_layer, self.target_crs, "Lane_" + lenkspur_layer.name(), self.output_dir)

            layer_group = get_layer_group(self.group_name)
            clean_layer_add(self.lenkspur_layer)
            layer_group.addLayer(self.lenkspur_layer)

            self.mapCanvas.setLayers(self.get_canvas_layers())
            self.mapCanvas.refresh()
            self._applied_lenkspur_id = lenkspur_layer.id()
            return True
        finally:
            self.btn_lenkspuren_laden.setEnabled(True)
    
    
    def af_laden(self):
        """Load the selected exclusion area (obstacle) layer, reproject to UTM, and add to the project."""
        if self.versuchstyp is Versuchstyp.KLEINPARZELLE:
            af_layer = self.mapLayerComboBox_AF_t3.currentLayer()
            btn = self.btn_af_laden_t3
        else:
            af_layer = self.mapLayerComboBox_AF.currentLayer()
            btn = self.btn_af_laden

        if af_layer is None or not is_valid_polygon_layer(af_layer):
            QMessageBox.critical(self, self.tr("Fehler"), self.tr("Ungültige Auswahl: Für 'Ausschlussfläche' muss ein Polygon-Vektorlayer ausgewählt werden."))
            return False

        if af_layer.id() == self._applied_af_id:
            return True

        btn.setEnabled(False)
        try:
            self.af_layer = reproject_layer(
                af_layer, self.target_crs, "AF_" + af_layer.name(), self.output_dir)

            self.af_layer.renderer().setSymbol(create_obstacle_symbol())
            self.af_layer.triggerRepaint()

            layer_group = get_layer_group(self.group_name)
            clean_layer_add(self.af_layer)
            layer_group.addLayer(self.af_layer)

            self.mapCanvas.setLayers(self.get_canvas_layers())
            self.mapCanvas.refresh()
            self._applied_af_id = af_layer.id()
            return True
        finally:
            btn.setEnabled(True)


    def on_num_vorgewende_valueChanged(self):
        if self.versuchstyp is Versuchstyp.KLEINPARZELLE:
            self.vorgewendebreite = self.num_vorgewende_t3.value()
        else:
            self.vorgewendebreite = self.num_vorgewende.value()
        if self.ohne_vorgewende:
            self.toggle_headland(True)

        
    def on_checkbox_vorgewende_toggle(self):
        if self.versuchstyp is Versuchstyp.KLEINPARZELLE:
            self.ohne_vorgewende = self.checkbox_vorgewende_t3.isChecked()
            self.vorgewendebreite = self.num_vorgewende_t3.value()
        else:
            self.ohne_vorgewende = self.checkbox_vorgewende.isChecked()
            self.vorgewendebreite = self.num_vorgewende.value()
        self.toggle_headland(self.ohne_vorgewende)



    def toggle_headland(self, checked):
        # cleanup first
        if self.innerLayer is not None:
            QgsProject.instance().removeMapLayers([self.innerLayer.id()])
        if self.bufferLayer is not None:
            QgsProject.instance().removeMapLayers([self.bufferLayer.id()])

        if checked:
            if not self.feld_layer:
                return False

            self.buffer_is_active = True
            self._create_headland_layers()
            self._add_headland_to_project()
        else:
            self.buffer_is_active = False
            self.innerLayer = None
            self.bufferLayer = None

        self.mapCanvas.setLayers(self.get_canvas_layers())
        self.mapCanvas.refresh()
        return True

    def _create_headland_layers(self):
        """Create inner and buffer memory layers from the field boundary."""
        distance = float(self.vorgewendebreite) * -1

        bufferLayer = QgsVectorLayer(
            "Polygon?crs={}".format(self.target_crs.authid()),
            self.tr("Vorgewende"), "memory")
        innerLayer = QgsVectorLayer(
            "Polygon?crs={}".format(self.target_crs.authid()),
            self.tr("Innerfläche"), "memory")

        bufferFeatures = []
        innerFeatures = []

        for feature in self.feld_layer.getFeatures():
            fgeom = QgsGeometry(feature.geometry())
            buffergeom = fgeom.buffer(distance, HEADLAND_BUFFER_SEGMENTS)
            diffgeom = fgeom.difference(buffergeom) if distance < 0 else buffergeom.difference(fgeom)

            bufferFeature = QgsFeature(feature.fields())
            bufferFeature.setGeometry(diffgeom)
            bufferFeatures.append(bufferFeature)

            innerFeature = QgsFeature(feature.fields())
            innerFeature.setGeometry(buffergeom)
            innerFeatures.append(innerFeature)

        bufferLayer.startEditing()
        bufferLayer.dataProvider().addFeatures(bufferFeatures)
        bufferLayer.commitChanges()
        bufferLayer.renderer().setSymbol(create_headland_pattern_symbol())
        bufferLayer.triggerRepaint()
        self.bufferLayer = bufferLayer

        innerLayer.startEditing()
        innerLayer.dataProvider().addFeatures(innerFeatures)
        innerLayer.commitChanges()
        innerLayer.renderer().setSymbol(create_headland_inner_symbol())
        innerLayer.triggerRepaint()
        self.innerLayer = innerLayer

    def _add_headland_to_project(self):
        """Export inner layer and add headland layers to the project."""
        output_path = os.path.join(self.output_dir, self.innerLayer.name() + ".shp")
        export_shapefile(self.innerLayer, output_path)

        layer_group = get_layer_group(self.group_name)
        clean_layer_add(self.innerLayer)
        clean_layer_add(self.bufferLayer)
        layer_group.addLayer(self.innerLayer)
        layer_group.addLayer(self.bufferLayer)

        self.plugin_instance.iface.layerTreeView().refreshLayerSymbology(self.innerLayer.id())
        self.plugin_instance.iface.layerTreeView().refreshLayerSymbology(self.bufferLayer.id())


    # TODO 5.1: Draw AB line

    def btn_linieziehen_clicked(self):
        QtWidgets.QMessageBox.information(self, self.tr("Los geht's"), self.tr("Sie können jetzt eine Linie auf der Karte zeichnen, um den Versuch auszurichten."))
        
        try:
            self.maptool.ab_line_created.disconnect(self.on_ab_line_created)
        except:
            pass
        self.maptool.ab_line_created.connect(self.on_ab_line_created)
        
        self.start()
        self.started = True
        self.maptool.init_rubber()
        self.maptool.init_snapping()
        return True

 

    def on_ab_line_created(self, geometry, point_a, point_b):
        """Handler called when AB line drawing is completed."""
        if point_a and point_b:
            # Add AB line to layers
            self.display_ab_line_on_map(geometry, self.target_crs)

            # Disable drawing mode and return to pan tool
            self.maptool.disable_rubber()
            self.maptool.disable_snapping()
            self.mapCanvas.setMapTool(self.pan_tool)
    
    def permutate(self, items, count):
        subsets = [[]]
        
        for el in items:
            last = len(subsets) - 1
            for i in range(last + 1):
                arr = subsets[i] + [el]
                if len(arr) == count:
                    subsets.append(arr)
        
        result = [x for x in subsets if len(x) == count]
        return result
    
    def generate_groups(self, variants_count, repetitions, keep_order=False):
        groups = []
        
        if len(groups) < repetitions:
            variants_arr = list(range(variants_count))
            groups.extend(self.permutate(variants_arr, variants_count))
            if not keep_order:
                random.shuffle(groups)
            if len(groups) < repetitions:
                diff = repetitions - len(groups)
                for i in range(diff):
                    shuffled = variants_arr[:]
                    random.shuffle(shuffled)
                    groups.append(shuffled)
            else:
                groups = groups[:repetitions]
        elif len(groups) > repetitions:
            groups = groups[:repetitions]
        
        return groups

    # TODO 5.2 Versuchsplan 2: Parzellen erstellen, randomisieren, Fahrspuren generieren, 
    def parzellenanlegen_clicked(self):
        try:

            if not self.feld_layer:
                QtWidgets.QMessageBox.warning(self, self.tr("Fehler"), self.tr("Bitte laden Sie zuerst eine Feldgrenze."))
                return False
            
            ab_line_data = self.maptool.get_ab_line()
            if not ab_line_data or not ab_line_data['geometry']:
                QtWidgets.QMessageBox.warning(self, self.tr("Fehler"), self.tr("Bitte zeichnen Sie zuerst eine AB-Linie auf der Karte."))
                return False
            
            field_geom = QgsGeometry.fromWkt(list(self.feld_layer.getFeatures())[0].geometry().asWkt())
            ab_line_geom = ab_line_data['geometry']
            
            field_crs = self.feld_layer.crs()
            
            width = self.num_parzellenbreite.value()
            if width <= 0:
                QtWidgets.QMessageBox.warning(self, self.tr("Fehler"), self.tr("Die Parzellenbreite muss größer als 0 sein."))
                return False
            planting_width = width / 2.0
            
            self.read_parameters()
            
            if not self.faktoren1:
                QtWidgets.QMessageBox.warning(self, self.tr("Fehler"), self.tr("Bitte geben Sie Faktorstufen ein."))
                return False
            
            variants = []
            for i, label in enumerate(self.faktoren1):
                variants.append({
                    'id': i,
                    'label': label,
                    'color': VARIANT_COLORS[i % len(VARIANT_COLORS)]
                })
            
            groups = self.generate_groups(len(variants), self.anzahl_x, keep_order=False)
            
            config = BlockConfig(
                width=width,
                planting_width=planting_width,
                variants=variants,
                groups=groups,
            )
            
            blocks = generate_blocks(
                field_geom,
                ab_line_geom,
                None,
                config,
            )
            
            self.display_blocks_on_map(blocks, field_crs)
            
            QtWidgets.QMessageBox.information(
                self, 
                self.tr("Erfolg"), 
                self.tr("{block_count} Blöcke mit insgesamt {plot_count} Parzellen erstellt.").format(
                    block_count=len(blocks),
                    plot_count=sum(len(b['plots']) for b in blocks),
                )
            )
            return True
            
        except Exception as e:
            import traceback
            logger.error("Error creating plots: %s", e, exc_info=True)
            error_msg = self.tr("Fehler beim Erstellen der Parzellen:") + f"\n\n{e}\n\n{traceback.format_exc()}"
            QtWidgets.QMessageBox.critical(self, self.tr("Fehler"), error_msg)
            return False 
    
    # TODO: old create for show casing, overtake options in clean code 
    def on_btn_parzellenanlegen_clicked_alt(self):
        if not self.feld_layer:
            QMessageBox.warning(self, self.tr("Fehler"), self.tr("Bitte laden Sie zuerst eine Feldgrenze."))
            return False
        if self.maptool.p0 is None:
            QMessageBox.warning(self, self.tr("Fehler"), self.tr("Bitte zeichnen Sie zuerst eine AB-Linie auf der Karte."))
            return False

        # Reset the rubber-band preview so it doesn't stack with the new one.
        # The variant plot_layer is intentionally kept — it was created by Randomize
        # and should only be removed by Randomize (when creating a new one) or Delete.
        self.maptool.all_points = []
        self.maptool.rbLines.reset()
        self.maptool.rbPlots.reset()

        self.read_parameters()
        self.maptool.create_plots(
            self.versuchstyp,
            self.feld_layer,
            self.anzahl_x,
            self.anzahl_y,
            self.parzellenbreite,
            self.parzellenlaenge,
            self.gap_x,
            self.gap_y,
            self.ohne_vorgewende,
            self.vorgewendebreite,            
        )
        return True 



    def btn_randomisieren_clicked(self):
        has_geometry = bool(self.maptool.all_points) or is_layer_valid(self.plot_layer)
        if not has_geometry:
            QMessageBox.warning(self, self.tr("Fehler"), self.tr("Bitte erstellen Sie zuerst Parzellen, bevor Sie randomisieren."))
            return False

        if self.maptool.all_points:
            # Normal path: build plots from maptool geometry and clip to boundary.
            if is_layer_valid(self.plot_layer):
                remove_layer(self.plot_layer)
                self.plot_layer = None

            plot_layer = self._create_plot_layer()
            feats = self._build_randomized_features()
            plot_layer.dataProvider().addFeatures(feats)
            plot_layer.commitChanges()
            self.plot_layer = self._intersect_plots_with_boundary(plot_layer)
        else:
            # Restore path: all_points lost (e.g. after project reload) but the
            # already-clipped plot_layer is present — re-shuffle variant assignments.
            self.plot_layer = self._rerandomize_existing_plot_layer()

        apply_categorized_variant_renderer(self.plot_layer, list(self.faktorstufen1))
        self._add_plot_layer_to_project()
        self.clear_maptool()

        # Keep core plots in sync with the new trial plot layout.
        if self.core_plot_layers and is_layer_valid(self.plot_layer):
            self._do_create_core_plots(self.plot_layer)

        return True

    def _rerandomize_existing_plot_layer(self):
        """Re-shuffle variant assignments on an already-clipped plot layer.

        Used when maptool.all_points is not available (e.g. after project reload)
        but self.plot_layer exists with saved geometries.
        """
        geometries = [f.geometry() for f in self.plot_layer.getFeatures()]
        crs_auth = self.plot_layer.crs().authid()
        remove_layer(self.plot_layer)
        self.plot_layer = None

        new_layer = QgsVectorLayer(
            f"Polygon?crs={crs_auth}", self.tr("Versuchsparzellen"), "memory")
        new_layer.dataProvider().addAttributes([
            QgsField("ID", QMetaType.Type.Int, "int"),
            QgsField("LABEL", QMetaType.Type.QString, "string"),
            QgsField("WDH", QMetaType.Type.Int, "int"),
            QgsField("FAKTOR1", QMetaType.Type.QString, "string"),
            QgsField("FAKTOR2", QMetaType.Type.QString, "string"),
            QgsField("VARIANTE", QMetaType.Type.QString, "string"),
        ])
        new_layer.updateFields()
        new_layer.startEditing()

        no_variants = len(self.faktorstufen1)
        array_variants = list(self.faktorstufen1)
        random.shuffle(array_variants)
        block_no = 1
        feats = []

        for fid, geom in enumerate(geometries, start=1):
            feature = QgsFeature(fid)
            feature.setGeometry(geom)
            variant = array_variants.pop(0)
            feature.setAttributes([
                fid, f"{block_no}_{variant}", block_no,
                self.faktor1, self.faktor2, variant,
            ])
            feats.append(feature)
            if fid % no_variants == 0:
                block_no += 1
            if not array_variants:
                array_variants = list(self.faktorstufen1)
                random.shuffle(array_variants)

        new_layer.dataProvider().addFeatures(feats)
        new_layer.commitChanges()
        return new_layer

    def _create_plot_layer(self):
        """Create an empty memory layer for plots with standard fields."""
        plot_layer = QgsVectorLayer(
            "Polygon?crs={}".format(self.target_crs.authid()),
            self.tr("Versuchsparzellen"), "memory")
        plot_layer.dataProvider().addAttributes([
            QgsField("ID", QMetaType.Type.Int, "int"),
            QgsField("LABEL", QMetaType.Type.QString, "string"),
            QgsField("WDH", QMetaType.Type.Int, "int"),
            QgsField("FAKTOR1", QMetaType.Type.QString, "string"),
            QgsField("FAKTOR2", QMetaType.Type.QString, "string"),
            QgsField("VARIANTE", QMetaType.Type.QString, "string"),
        ])
        plot_layer.updateFields()
        plot_layer.startEditing()
        return plot_layer

    def _build_randomized_features(self):
        """Build randomized plot features from maptool geometry."""
        feats = []
        no_variants = len(self.faktorstufen1)
        array_variants = list(self.faktorstufen1)
        random.shuffle(array_variants)
        block_no = 1
        fid = 1

        for p in self.maptool.all_points:
            poly = QgsPolygon()
            linestring = QgsLineString(p)
            linestring.close()
            poly.setExteriorRing(linestring)
            feature = QgsFeature(fid)
            feature.setGeometry(poly)

            variant = array_variants.pop(0)
            feature.setAttributes([
                fid, f"{block_no}_{variant}", block_no,
                f"{self.faktor1}", self.faktor2, variant,
            ])
            feats.append(feature)

            if fid % no_variants == 0:
                block_no += 1
            fid += 1

            if not array_variants:
                array_variants = list(self.faktorstufen1)
                random.shuffle(array_variants)

        return feats

    def _intersect_plots_with_boundary(self, plot_layer):
        """Clip plots to the inner boundary (or field boundary as fallback), then subtract exclusion areas."""
        clip_layer = self.innerLayer
        if clip_layer is None or not clip_layer.isValid():
            clip_layer = self.feld_layer
        if clip_layer is None or not clip_layer.isValid():
            logger.warning("Inner boundary and field boundary not set. No clipping possible.")
            return plot_layer

        context = QgsProcessingContext()
        context.setProject(QgsProject.instance())
        plots_extracted = processing.run("native:intersection", {
            'INPUT': plot_layer,
            'OVERLAY': clip_layer,
            'INPUT_FIELDS': [], 'OVERLAY_FIELDS': [],
            'OVERLAY_FIELDS_PREFIX': '',
            'OUTPUT': 'TEMPORARY_OUTPUT',
            'GRID_SIZE': None,
        }, context=context, feedback=QgsProcessingFeedback())["OUTPUT"]

        # Subtract exclusion areas (obstacles) if present
        if is_layer_valid(self.af_layer) and self.af_layer.featureCount() > 0:
            plots_extracted = processing.run("native:difference", {
                'INPUT': plots_extracted,
                'OVERLAY': self.af_layer,
                'OUTPUT': 'TEMPORARY_OUTPUT',
                'GRID_SIZE': None,
            }, context=context, feedback=QgsProcessingFeedback())["OUTPUT"]

        plots_extracted.setName(self.tr("Versuchsparzellen"))
        return plots_extracted

    def _add_plot_layer_to_project(self):
        """Add the plot layer to the map canvas and project tree."""
        # Register with project FIRST so the layer is project-owned before
        # being assigned to the canvas.  Setting canvas layers before addMapLayer
        # can cause QGIS to silently drop the layer when the project tree changes.
        layer_group = get_layer_group(self.group_name)
        QgsProject.instance().addMapLayer(self.plot_layer, False)
        layer_group.addLayer(self.plot_layer)

        self.mapCanvas.setLayers(self.get_canvas_layers())
        self.mapCanvas.refresh()
        self.plugin_instance.iface.layerTreeView().refreshLayerSymbology(self.plot_layer.id())
        self.plugin_instance.iface.mapCanvas().refresh()
        
    def btn_parzellenloeschen_clicked(self):
        #QtWidgets.QMessageBox.information(self, "TODO", "Parzellen löschen")
        if self.plot_layer:
            QgsProject.instance().removeMapLayer(self.plot_layer)
            self.plot_layer = None
            self.mapCanvas.setLayers(self.get_canvas_layers())
            self.mapCanvas.refresh()
            if self.plugin_instance and self.plugin_instance.iface:
                self.plugin_instance.iface.mapCanvas().refresh()
        
        self.maptool.all_points = []
        self.clear_maptool()
        
    
    def clear_maptool(self):
        self.maptool.hide()
        self.mapCanvas.unsetMapTool(self.maptool)
        return True
        

    # ── Core Plots (Tab 4) ──────────────────────────────────────────────

    def _preselect_t4_layers(self):
        """Pre-populate tab-4 layer combos from current plugin state."""
        mapping = [
            (self.cmb_feldgrenze_t4, self.feld_layer),
            (self.cmb_inner_t4, self.innerLayer),
            (self.cmb_af_t4, self.af_layer),
            (self.cmb_plots_t4, self.plot_layer),
        ]
        for combo, layer in mapping:
            if is_layer_valid(layer):
                combo.setLayer(layer)

    def button_back_t4_clicked(self):
        """Navigate back from core plots tab to the planning tab."""
        if self.versuchstyp is Versuchstyp.KLEINPARZELLE:
            self.tabWidget.setCurrentIndex(2)
        else:
            self.tabWidget.setCurrentIndex(1)

    def btn_next_t4_clicked(self):
        """Navigate from core plots tab to print/export tab."""
        self.tabWidget.setTabEnabled(4, True)
        self.tabWidget.setCurrentIndex(4)

    def btn_load_json_t4_clicked(self):
        """Load a JSON file to prefill core plot parameters."""
        json_path, _ = QtWidgets.QFileDialog.getOpenFileName(
            self, self.tr("JSON-Parameter laden"), self.output_dir, "JSON (*.json)"
        )
        if not json_path:
            return

        try:
            with open(json_path, "r", encoding="utf-8") as f:
                params = json.load(f)
        except (json.JSONDecodeError, OSError) as e:
            QMessageBox.warning(self, self.tr("Fehler"),
                                self.tr("JSON konnte nicht geladen werden: {error}").format(error=str(e)))
            return

        if "core_prefix" in params:
            self.txt_prefix_t4.setText(str(params["core_prefix"]))
        if "core_length" in params:
            self.num_core_length_t4.setValue(float(params["core_length"]))
        if "core_width" in params:
            self.num_core_width_t4.setValue(float(params["core_width"]))
        if "core_placement" in params:
            placement = str(params["core_placement"]).lower()
            idx_map = {"center": 0, "bottom": 1, "top": 2}
            self.cmb_placement_t4.setCurrentIndex(idx_map.get(placement, 0))

    def btn_create_core_t4_clicked(self):
        """Create core plots from the selected plots layer and add to project."""
        plots_layer = self.cmb_plots_t4.currentLayer()
        if not is_valid_polygon_layer(plots_layer):
            QMessageBox.warning(self, self.tr("Warnung"),
                                self.tr("Bitte wählen Sie einen gültigen Parzellen-Layer aus."))
            return
        self._do_create_core_plots(plots_layer)

    def _do_create_core_plots(self, plots_layer):
        """Generate core plots from plots_layer using current UI settings and add to project."""
        # Need AB line for orientation
        ab_geom = None
        if is_layer_valid(self.ab_line_layer):
            feats = list(self.ab_line_layer.getFeatures())
            if feats:
                ab_geom = feats[0].geometry()
        if not ab_geom or ab_geom.isEmpty():
            QMessageBox.warning(self, self.tr("Warnung"),
                                self.tr("Keine AB-Linie gefunden. Bitte erstellen Sie zuerst Parzellen."))
            return

        prefix = self.txt_prefix_t4.text().strip()
        if not prefix:
            prefix = "core_"

        core_length = self.num_core_length_t4.value()
        core_width = self.num_core_width_t4.value()

        placement_idx = self.cmb_placement_t4.currentIndex()
        placement_map = {0: "center", 1: "bottom", 2: "top"}
        placement = placement_map.get(placement_idx, "center")

        core_features = generate_core_plots(
            plots_layer, ab_geom, core_width, core_length, placement
        )

        if not core_features:
            QMessageBox.warning(self, self.tr("Warnung"),
                                self.tr("Es konnten keine Kernparzellen erstellt werden."))
            return

        # Remove previous core plot layers
        if self.core_plot_layers:
            old_ids = [cl.id() for cl in self.core_plot_layers if is_layer_valid(cl)]
            if old_ids:
                QgsProject.instance().removeMapLayers(old_ids)
            self.core_plot_layers = []

        # Create memory layer for core plots
        crs = plots_layer.crs()
        layer_name = f"{prefix}plots"
        core_layer = QgsVectorLayer(
            f"Polygon?crs={crs.authid()}", layer_name, "memory"
        )
        provider = core_layer.dataProvider()
        provider.addAttributes([
            QgsField("ID", QMetaType.Type.Int, "int"),
            QgsField("LABEL", QMetaType.Type.QString, "string"),
            QgsField("WDH", QMetaType.Type.Int, "int"),
            QgsField("FAKTOR1", QMetaType.Type.QString, "string"),
            QgsField("FAKTOR2", QMetaType.Type.QString, "string"),
            QgsField("VARIANTE", QMetaType.Type.QString, "string"),
        ])
        core_layer.updateFields()

        core_layer.startEditing()
        for feat in core_features:
            new_feat = QgsFeature(core_layer.fields())
            new_feat.setGeometry(feat.geometry())
            attrs = feat.attributes()
            new_feat.setAttributes(attrs[:6] if len(attrs) >= 6 else attrs)
            provider.addFeature(new_feat)
        core_layer.commitChanges()

        # Apply variant renderer
        apply_categorized_variant_renderer(core_layer, list(self.faktorstufen1))

        # Add to project
        layer_group = get_layer_group(self.group_name)
        # Remove any pre-existing layer with the same name to avoid duplicates.
        for _dup in QgsProject.instance().mapLayersByName(layer_name):
            QgsProject.instance().removeMapLayers([_dup.id()])
        QgsProject.instance().addMapLayer(core_layer, False)
        # Insert just above the trial plots layer.
        self._insert_core_layer_in_group(layer_group, core_layer)
        self.core_plot_layers.append(core_layer)

        # Update canvas
        self.mapCanvas.setLayers(self.get_canvas_layers())
        self.mapCanvas.refresh()
        if self.plugin_instance and self.plugin_instance.iface:
            self.plugin_instance.iface.layerTreeView().refreshLayerSymbology(core_layer.id())
            self.plugin_instance.iface.mapCanvas().refresh()

        logger.info("Created %d core plots in layer '%s'", len(core_features), layer_name)

    def btn_save_t4_clicked(self):
        """Save core plots tab — same full save as other planning tabs."""
        if not self.core_plot_layers:
            QMessageBox.warning(self, self.tr("Warnung"),
                                self.tr("Keine Kernparzellen zum Speichern."))
            return
        self.on_speicher_button_clicked()

    def _insert_core_layer_in_group(self, layer_group, layer):
        """Insert a core plot layer just above the trial plots layer in the group."""
        new_node = QgsLayerTreeLayer(layer)
        if is_layer_valid(self.plot_layer):
            for i, child in enumerate(layer_group.children()):
                if isinstance(child, QgsLayerTreeLayer) and child.layer() == self.plot_layer:
                    layer_group.insertChildNode(i, new_node)
                    return
        # Fallback: append at bottom of group
        layer_group.insertChildNode(-1, new_node)

    def _persist_core_plot_layers(self):
        """Save in-memory core plot layers to shapefiles in output_dir."""
        layer_group = get_layer_group(self.group_name)
        for i, layer in enumerate(self.core_plot_layers):
            if not is_layer_valid(layer):
                continue
            if self._layer_is_persisted(layer):
                continue
            shp_path = os.path.join(self.output_dir, layer.name() + ".shp")
            success, _ = export_shapefile(layer, shp_path)
            if success:
                new_layer = QgsVectorLayer(shp_path, layer.name(), "ogr")
                if new_layer.isValid():
                    apply_categorized_variant_renderer(new_layer, list(self.faktorstufen1))
                    remove_layer(layer)
                    self.core_plot_layers[i] = new_layer
                    QgsProject.instance().addMapLayer(new_layer, False)
                    self._insert_core_layer_in_group(layer_group, new_layer)
        self.core_plot_layers = [l for l in self.core_plot_layers if is_layer_valid(l)]
        self.mapCanvas.setLayers(self.get_canvas_layers())
        self.mapCanvas.refresh()
        if self.plugin_instance and self.plugin_instance.iface:
            self.plugin_instance.iface.mapCanvas().refresh()

    # TODO 7: Export: Format, Speichern

    def _preselect_t5_layers(self):
        """Pre-populate the tab-5 layer combos with the layers currently tracked by the plugin."""
        mapping = [
            (self.cmb_feldgrenze_t5, self.feld_layer),
            (self.cmb_headland_t5,   self.bufferLayer),
            (self.cmb_inner_t5,      self.innerLayer),
            (self.cmb_af_t5,         self.af_layer),
            (self.cmb_plots_t5,      self.plot_layer),
            (self.cmb_core_t5,       self.core_plot_layers[0] if self.core_plot_layers else None),
            (self.cmb_guidance_t5,   self.ab_line_layer),
        ]
        for combo, layer in mapping:
            if is_layer_valid(layer):
                combo.setLayer(layer)

    def _on_tab_changed(self, index):
        """Update the map canvas when switching tabs."""
        if index == 3:  # Tab 4: Core Plots
            self._preselect_t4_layers()
            self.mapCanvas.setLayers(self.get_canvas_layers())
            self.mapCanvas.refresh()
        elif index == 4:  # Tab 5: Print / Export
            self._preselect_t5_layers()
            self._update_t5_canvas()
        else:
            self.mapCanvas.setLayers(self.get_canvas_layers())
            self.mapCanvas.refresh()

    def _update_t5_canvas(self):
        """Refresh the map canvas to show layers currently selected in the export tab."""
        # Build list in draw order: top layers first, background last.
        # Combos are ordered field→headland→inner→af→plots→guidance;
        # we reverse so guidance (top) comes first and field (bottom) comes last.
        layers = []
        for combo in [
            self.cmb_guidance_t5, self.cmb_core_t5, self.cmb_plots_t5, self.cmb_af_t5,
            self.cmb_inner_t5, self.cmb_headland_t5, self.cmb_feldgrenze_t5,
        ]:
            layer = combo.currentLayer()
            if layer and layer.isValid():
                layers.append(layer)
        if is_layer_valid(self.osm_layer):
            layers.append(self.osm_layer)
        if layers:
            self.mapCanvas.setLayers(layers)
            self.mapCanvas.refresh()

    def _browse_export_t5(self):
        """Open a Save dialog so the user can choose the output ZIP file path."""
        path, _ = QtWidgets.QFileDialog.getSaveFileName(
            self,
            self.tr("Speicherort für Export wählen"),
            self.output_dir,
            self.tr("ZIP-Dateien (*.zip)"),
        )
        if path:
            if not path.lower().endswith(".zip"):
                path += ".zip"
            self.txt_export_path_t5.setText(path)

    def _export_t5(self):
        """Export all selected layers from the export tab as shapefiles in EPSG:4326 into a ZIP."""
        zip_path = self.txt_export_path_t5.text().strip()
        if not zip_path:
            QMessageBox.warning(
                self,
                self.tr("Warnung"),
                self.tr("Bitte wählen Sie zuerst einen Speicherort."),
            )
            return

        layers = []
        for combo in [
            self.cmb_feldgrenze_t5, self.cmb_headland_t5, self.cmb_inner_t5,
            self.cmb_af_t5, self.cmb_plots_t5, self.cmb_core_t5, self.cmb_guidance_t5,
        ]:
            layer = combo.currentLayer()
            if layer and layer.isValid():
                layers.append(layer)

        if not layers:
            QMessageBox.warning(
                self,
                self.tr("Warnung"),
                self.tr("Bitte wählen Sie mindestens einen Layer zum Exportieren aus."),
            )
            return

        try:
            success, failed = export_layers_to_zip(layers, zip_path)
        except Exception as e:
            logger.error("Export failed: %s", e, exc_info=True)
            QMessageBox.critical(
                self,
                self.tr("Fehler"),
                self.tr("Export fehlgeschlagen: {error}").format(error=str(e)),
            )
            return

        if not success:
            QMessageBox.critical(
                self,
                self.tr("Fehler"),
                self.tr("Keine Layer konnten exportiert werden."),
            )
            return

        msg = self.tr("Export erfolgreich!\n\nZIP-Datei: {path}").format(path=zip_path)
        if failed:
            msg += "\n\n" + self.tr("Fehlgeschlagene Layer: {layers}").format(layers=", ".join(failed))
        QMessageBox.information(self, self.tr("Export"), msg)

    # --- Print / PDF ---

    _PAGE_SIZES_MM = {
        "DIN A4 Portrait":  (210.0, 297.0),
        "DIN A4 Landscape": (297.0, 210.0),
        "DIN A3 Portrait":  (297.0, 420.0),
        "DIN A3 Landscape": (420.0, 297.0),
    }

    def _update_print_button_state(self):
        """Enable Create PDF only when a format and a file path are both set."""
        has_format = self.cmb_print_format_t5.currentIndex() > 0
        has_path = bool(self.txt_print_path_t5.text().strip())
        self.btn_print_t5.setEnabled(has_format and has_path)

    def _browse_print_t5(self):
        """Open a Save dialog so the user can choose the output PDF file path."""
        path, _ = QtWidgets.QFileDialog.getSaveFileName(
            self,
            self.tr("Speicherort für PDF wählen"),
            self.output_dir,
            self.tr("PDF-Dateien (*.pdf)"),
        )
        if path:
            if not path.lower().endswith(".pdf"):
                path += ".pdf"
            self.txt_print_path_t5.setText(path)

    def _print_t5(self):
        """Render selected layers to a PDF using a QGIS print layout."""
        format_text = self.cmb_print_format_t5.currentText()
        pdf_path = self.txt_print_path_t5.text().strip()
        page_w, page_h = self._PAGE_SIZES_MM.get(format_text, (210.0, 297.0))

        # Layers in draw order: top → bottom, OSM as background
        layers = []
        for combo in [
            self.cmb_guidance_t5, self.cmb_core_t5, self.cmb_plots_t5, self.cmb_af_t5,
            self.cmb_inner_t5, self.cmb_headland_t5, self.cmb_feldgrenze_t5,
        ]:
            layer = combo.currentLayer()
            if layer and layer.isValid():
                layers.append(layer)
        if is_layer_valid(self.osm_layer):
            layers.append(self.osm_layer)

        if not layers:
            QMessageBox.warning(
                self,
                self.tr("Warnung"),
                self.tr("Bitte wählen Sie mindestens einen Layer zum Drucken aus."),
            )
            return

        # --- Compute print extent FIRST so scale bar and map item are consistent ---
        canvas_crs = self.mapCanvas.mapSettings().destinationCrs()
        transform_context = QgsProject.instance().transformContext()

        def _extent_in_canvas_crs(layer):
            """Return layer extent in canvas_crs, or None on any failure."""
            if not is_layer_valid(layer):
                return None
            try:
                ext = layer.extent()
                if ext.isNull() or ext.isEmpty():
                    return None
                src_crs = layer.crs()
                if src_crs.isValid() and src_crs != canvas_crs:
                    ct = QgsCoordinateTransform(src_crs, canvas_crs, transform_context)
                    ext = ct.transformBoundingBox(ext)
                if ext.isNull() or ext.isEmpty():
                    return None
                return ext
            except Exception:
                return None

        # Priority: field combo → plugin feld_layer → canvas extent
        print_extent = _extent_in_canvas_crs(self.cmb_feldgrenze_t5.currentLayer())
        if print_extent is None:
            print_extent = _extent_in_canvas_crs(self.feld_layer)
        if print_extent is None:
            print_extent = self.mapCanvas.extent()

        pad = max(print_extent.width(), print_extent.height()) * 0.05
        print_extent.grow(pad)

        project = QgsProject.instance()
        layout = QgsPrintLayout(project)
        layout.initializeDefaults()

        # Page size
        page = layout.pageCollection().pages()[0]
        page.setPageSize(QgsLayoutSize(page_w, page_h, QgsUnitTypes.LayoutMillimeters))

        # Layout geometry constants (all in mm)
        margin = 10.0
        gap = 3.0
        _CHARS_PER_LINE = 250
        _LINE_HEIGHT_MM = 5.0
        _MAX_LINES = 6
        fragestellung = self.txt_fragestellung.toPlainText().strip()
        # Truncate to max lines and append ellipsis if needed
        max_chars = _CHARS_PER_LINE * _MAX_LINES
        if len(fragestellung) > max_chars:
            fragestellung = fragestellung[:max_chars - 1].rstrip() + "…"
        n_lines = max(1, math.ceil(len(fragestellung) / _CHARS_PER_LINE))
        title_h = n_lines * _LINE_HEIGHT_MM
        right_panel_w = 50.0
        north_size = 20.0
        scale_h = 12.0
        map_left = margin
        map_top = margin + title_h + gap
        map_w = page_w - 2 * margin - gap - right_panel_w
        map_h = page_h - map_top - gap - scale_h - 5.0  # 5 mm bottom margin
        scale_top = map_top + map_h + gap
        right_x = map_left + map_w + gap
        # North arrow sits at the very bottom of the right panel
        north_top = map_top + map_h - north_size
        legend_h = map_h - north_size - gap

        # --- Trial question label ---
        # Width limited to map_w so it doesn't overlap the right panel
        title_label = QgsLayoutItemLabel(layout)
        layout.addLayoutItem(title_label)
        title_label.setText(fragestellung)
        title_label.setFont(QFont("Arial", 9))
        title_label.setHAlign(Qt.AlignLeft)
        title_label.setVAlign(Qt.AlignTop)
        title_label.attemptMove(QgsLayoutPoint(margin, margin, QgsUnitTypes.LayoutMillimeters))
        title_label.attemptResize(QgsLayoutSize(map_w, title_h, QgsUnitTypes.LayoutMillimeters))

        # --- Map item ---
        map_item = QgsLayoutItemMap(layout)
        layout.addLayoutItem(map_item)
        map_item.attemptMove(QgsLayoutPoint(map_left, map_top, QgsUnitTypes.LayoutMillimeters))
        map_item.attemptResize(QgsLayoutSize(map_w, map_h, QgsUnitTypes.LayoutMillimeters))
        map_item.setKeepLayerSet(True)
        map_item.setLayers(layers)
        map_item.setCrs(canvas_crs)
        map_item.zoomToExtent(print_extent)

        # --- North arrow (bottom of right panel, bundled SVG) ---
        north = QgsLayoutItemPicture(layout)
        layout.addLayoutItem(north)
        north_svg = os.path.join(os.path.dirname(__file__), 'icons', 'north_arrow.svg')
        north.setPicturePath(north_svg)
        north.setNorthMode(QgsLayoutItemPicture.GridNorth)
        north.setLinkedMap(map_item)
        north.attemptMove(QgsLayoutPoint(right_x, north_top, QgsUnitTypes.LayoutMillimeters))
        north.attemptResize(QgsLayoutSize(north_size, north_size, QgsUnitTypes.LayoutMillimeters))

        # --- Legend (core_plots excluded) ---
        legend = QgsLayoutItemLegend(layout)
        layout.addLayoutItem(legend)
        legend.setLinkedMap(map_item)
        # Disable auto-update BEFORE modifying the model so the changes stay
        # local to the legend and do NOT alter the project's layer tree.
        legend.setAutoUpdateModel(False)
        legend.updateLegend()
        core_layer = self.cmb_core_t5.currentLayer()
        if core_layer:
            for node in legend.model().rootGroup().findLayers():
                if node.layerId() == core_layer.id():
                    node.parent().removeChildNode(node)
                    break
        # Legend starts at same y as map; zero internal top margin
        from qgis.core import QgsLegendStyle
        legend.rstyle(QgsLegendStyle.Group).setMargin(QgsLegendStyle.Top, 0.0)
        legend.rstyle(QgsLegendStyle.Subgroup).setMargin(QgsLegendStyle.Top, 0.0)
        legend.rstyle(QgsLegendStyle.Title).setMargin(QgsLegendStyle.Top, 0.0)
        legend.attemptMove(QgsLayoutPoint(right_x, map_top, QgsUnitTypes.LayoutMillimeters))
        legend.attemptResize(QgsLayoutSize(right_panel_w, legend_h, QgsUnitTypes.LayoutMillimeters))

        # --- Scale bar ---
        # Compute a nice round segment size from the known print extent so that
        # the bar always shows meaningful distances instead of "0 |".
        scalebar = QgsLayoutItemScaleBar(layout)
        layout.addLayoutItem(scalebar)
        scalebar.setLinkedMap(map_item)
        scalebar.setNumberOfSegments(4)
        scalebar.setNumberOfSegmentsLeft(0)
        scalebar.setUnits(QgsUnitTypes.DistanceMeters)
        scalebar.setUnitLabel("m")
        # Round to the nearest order-of-magnitude step
        raw_seg = print_extent.width() / 4.0
        magnitude = 10 ** math.floor(math.log10(max(raw_seg, 1.0)))
        nice_seg = round(raw_seg / magnitude) * magnitude
        scalebar.setUnitsPerSegment(max(nice_seg, 1.0))
        scalebar.attemptMove(QgsLayoutPoint(margin, scale_top, QgsUnitTypes.LayoutMillimeters))
        scalebar.attemptResize(QgsLayoutSize(map_w * 0.6, scale_h, QgsUnitTypes.LayoutMillimeters))

        try:
            exporter = QgsLayoutExporter(layout)
            settings = QgsLayoutExporter.PdfExportSettings()
            result = exporter.exportToPdf(pdf_path, settings)
            if result == QgsLayoutExporter.Success:
                QMessageBox.information(
                    self,
                    self.tr("Drucken"),
                    self.tr("PDF erfolgreich erstellt:\n{path}").format(path=pdf_path),
                )
            else:
                QMessageBox.critical(
                    self,
                    self.tr("Fehler"),
                    self.tr("PDF konnte nicht erstellt werden (Fehlercode {code}).").format(code=result),
                )
        except Exception as e:
            logger.error("PDF export failed: %s", e, exc_info=True)
            QMessageBox.critical(
                self,
                self.tr("Fehler"),
                self.tr("PDF konnte nicht erstellt werden: {error}").format(error=str(e)),
            )

    def btn_finish_t5_clicked(self):
        """Save the final JSON log and close the planning dialog."""
        self.on_speicher_button_clicked()
        logger.info("Planning finished — closing dialog.")
        self.close()

    def _layer_is_persisted(self, layer):
        """Return True if layer is already saved as a file inside output_dir."""
        if layer.dataProvider().name() != "ogr":
            return False
        src = os.path.normcase(os.path.normpath(layer.source().split("|")[0]))
        out = os.path.normcase(os.path.normpath(self.output_dir))
        return src.startswith(out + os.sep) or src.startswith(out + "/")

    def on_speicher_button_clicked(self):
        """Save all parameters to JSON and persist in-memory layers as shapefiles."""
        if not is_layer_valid(self.plot_layer):
            QMessageBox.warning(self, self.tr("Warnung"), self.tr("Keine Versuchsparzellen zum Speichern."))
            return False

        # --- 1. Collect parameters ---
        params = {
            "versuchstyp": self.versuchstyp.name,
            "fragestellung": self.txt_fragestellung.toPlainText().strip(),
            "faktor1": self.faktor1,
            "faktor2": self.faktor2,
            "faktorstufen1_raw": self.txt_faktorstufen1.text().strip(),
            "faktorstufen": self.faktorstufen1,
            "n_faktoren": self.int_faktoren.value(),
            "wiederholungen": self.wdh,
            "parzellenbreite": self.parzellenbreite,
            "parzellenlaenge": self.parzellenlaenge,
            "gap_x": self.gap_x,
            "gap_y": self.gap_y,
            "vorgewendebreite": self.vorgewendebreite,
            "ohne_vorgewende": self.ohne_vorgewende,
            "anzahl_x": self.anzahl_x,
            "anzahl_y": self.anzahl_y,
            "core_prefix": self.txt_prefix_t4.text(),
            "core_length": self.num_core_length_t4.value(),
            "core_width": self.num_core_width_t4.value(),
            "core_placement": self.cmb_placement_t4.currentIndex(),
        }

        if self.int_faktoren.value() == 2:
            params["faktorstufen2_raw"] = self.txt_faktorstufen2.text().strip()

        # Add layer file references
        layer_files = {}

        # --- 2. Persist in-memory layers ---
        layer_group = get_layer_group(self.group_name)

        # Plot layer
        if self._layer_is_persisted(self.plot_layer):
            layer_files["plot_layer"] = self.plot_layer.source().split("|")[0]
            params["plot_layer_name"] = self.plot_layer.name()
        else:
            plot_file = os.path.join(self.output_dir, self.plot_layer.name() + ".shp")
            success, msg = export_shapefile(self.plot_layer, plot_file)
            if success:
                saved_plot = QgsVectorLayer(plot_file, self.plot_layer.name(), "ogr")
                if saved_plot.isValid():
                    apply_categorized_variant_renderer(saved_plot, list(self.faktorstufen1))
                    remove_layer(self.plot_layer)
                    self.plot_layer = saved_plot
                    clean_layer_add(self.plot_layer)
                    layer_group.addLayer(self.plot_layer)
                layer_files["plot_layer"] = plot_file
                params["plot_layer_name"] = self.plot_layer.name()

        # AB line layer
        if is_layer_valid(self.ab_line_layer):
            if self._layer_is_persisted(self.ab_line_layer):
                layer_files["ab_line_layer"] = self.ab_line_layer.source().split("|")[0]
                params["ab_line_layer_name"] = self.ab_line_layer.name()
            else:
                ab_file = os.path.join(self.output_dir, self.ab_line_layer.name() + ".shp")
                success, msg = export_shapefile(self.ab_line_layer, ab_file)
                if success:
                    saved_ab = QgsVectorLayer(ab_file, self.ab_line_layer.name(), "ogr")
                    if saved_ab.isValid():
                        saved_ab.renderer().setSymbol(create_ab_line_symbol())
                        remove_layer(self.ab_line_layer)
                        self.ab_line_layer = saved_ab
                        clean_layer_add(self.ab_line_layer)
                        layer_group.addLayer(self.ab_line_layer)
                    layer_files["ab_line_layer"] = ab_file
                    params["ab_line_layer_name"] = self.ab_line_layer.name()
        # Save AB line endpoints so maptool state can be restored
        if is_layer_valid(self.ab_line_layer):
            feats = list(self.ab_line_layer.getFeatures())
            if feats:
                geom = feats[0].geometry()
                if geom.isMultipart():
                    parts = geom.asMultiPolyline()
                    line = parts[0] if parts else []
                else:
                    line = geom.asPolyline()
                if len(line) >= 2:
                    params["ab_pt_a"] = [line[0].x(), line[0].y()]
                    params["ab_pt_b"] = [line[-1].x(), line[-1].y()]

        # Inner area layer (headland)
        if is_layer_valid(self.innerLayer):
            if self._layer_is_persisted(self.innerLayer):
                layer_files["inner_layer"] = self.innerLayer.source().split("|")[0]
                params["inner_layer_name"] = self.innerLayer.name()
            else:
                inner_file = os.path.join(self.output_dir, self.innerLayer.name() + ".shp")
                success, msg = export_shapefile(self.innerLayer, inner_file)
                if success:
                    saved_inner = QgsVectorLayer(inner_file, self.innerLayer.name(), "ogr")
                    if saved_inner.isValid():
                        saved_inner.renderer().setSymbol(create_headland_inner_symbol())
                        remove_layer(self.innerLayer)
                        self.innerLayer = saved_inner
                        clean_layer_add(self.innerLayer)
                        layer_group.addLayer(self.innerLayer)
                    layer_files["inner_layer"] = inner_file
                    params["inner_layer_name"] = self.innerLayer.name()

        # Buffer layer (headland pattern)
        if is_layer_valid(self.bufferLayer):
            if self._layer_is_persisted(self.bufferLayer):
                layer_files["buffer_layer"] = self.bufferLayer.source().split("|")[0]
                params["buffer_layer_name"] = self.bufferLayer.name()
            else:
                buffer_file = os.path.join(self.output_dir, self.bufferLayer.name() + ".shp")
                success, msg = export_shapefile(self.bufferLayer, buffer_file)
                if success:
                    saved_buffer = QgsVectorLayer(buffer_file, self.bufferLayer.name(), "ogr")
                    if saved_buffer.isValid():
                        saved_buffer.renderer().setSymbol(create_headland_pattern_symbol())
                        remove_layer(self.bufferLayer)
                        self.bufferLayer = saved_buffer
                        clean_layer_add(self.bufferLayer)
                        layer_group.addLayer(self.bufferLayer)
                    layer_files["buffer_layer"] = buffer_file
                    params["buffer_layer_name"] = self.bufferLayer.name()

        # Field and guidance layers are already file-based
        if is_layer_valid(self.feld_layer):
            layer_files["feld_layer"] = self.feld_layer.source()
            params["feld_layer_name"] = self.feld_layer.name()
        if is_layer_valid(self.lenkspur_layer):
            layer_files["lenkspur_layer"] = self.lenkspur_layer.source()
            params["lenkspur_layer_name"] = self.lenkspur_layer.name()
        if is_layer_valid(self.af_layer):
            layer_files["af_layer"] = self.af_layer.source()
            params["af_layer_name"] = self.af_layer.name()

        # Persist any existing core plot layers first so their paths are available
        if self.core_plot_layers:
            self._persist_core_plot_layers()

        # Core plot layers (list)
        core_entries = []
        for cl in self.core_plot_layers:
            if is_layer_valid(cl) and self._layer_is_persisted(cl):
                core_entries.append({"path": cl.source().split("|")[0], "name": cl.name()})
        if core_entries:
            layer_files["core_plot_layers"] = core_entries

        # Save original user-selected source layer IDs for combo box restore
        if self._applied_feld_id:
            params["selected_feld_id"] = self._applied_feld_id
        if self._applied_lenkspur_id:
            params["selected_lenkspur_id"] = self._applied_lenkspur_id
        if self._applied_af_id:
            params["selected_af_id"] = self._applied_af_id

        params["layer_files"] = layer_files

        # --- 3. Save JSON ---
        json_path = os.path.join(self.output_dir, "ofe_parameter.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(params, f, ensure_ascii=False, indent=2)

        # --- 4. Refresh ---
        self.mapCanvas.setLayers(self.get_canvas_layers())
        self.mapCanvas.refresh()
        iface = self.plugin_instance.iface
        for lyr in [self.plot_layer, self.ab_line_layer, self.innerLayer, self.bufferLayer]:
            if is_layer_valid(lyr):
                lyr.triggerRepaint()
                iface.layerTreeView().refreshLayerSymbology(lyr.id())
        iface.mapCanvas().refresh()

        logger.info("Saved experiment to %s", self.output_dir)

        # Enable Core Plots tab after saving
        self.tabWidget.setTabEnabled(3, True)
        self._preselect_t4_layers()

        return True

    # TODO 8: Drucken: Template, Kartenelemente, PDF


    # TODO 9: Helper functions

    def geojson_to_wkt(self, geojson):
        geom_type = geojson['type']
        coords = geojson['coordinates']
        
        if geom_type == 'LineString':
            points = [f"{c[0]} {c[1]}" for c in coords]
            return f"LINESTRING({', '.join(points)})"
        elif geom_type == 'MultiPolygon':
            polygons = []
            for polygon in coords:
                rings = []
                for ring in polygon:
                    points = [f"{c[0]} {c[1]}" for c in ring]
                    rings.append(f"({', '.join(points)})")
                polygons.append(f"({', '.join(rings)})")
            return f"MULTIPOLYGON({', '.join(polygons)})"
        return ""

    def display_ab_line_on_map(self, geometry, crs):
        """Display the AB line as a persistent layer on the map."""
        # Remove existing AB line layer if it exists
        if is_layer_valid(self.ab_line_layer):
            remove_layer(self.ab_line_layer)
            self.ab_line_layer = None

        # Create memory layer for AB line
        self.ab_line_layer = QgsVectorLayer(
            f"LineString?crs={crs.authid()}",
            self.tr("AB-Linie"),
            "memory"
        )

        provider = self.ab_line_layer.dataProvider()
        self.ab_line_layer.startEditing()

        feature = QgsFeature()
        feature.setGeometry(geometry)
        provider.addFeature(feature)

        self.ab_line_layer.commitChanges()

        self.ab_line_layer.renderer().setSymbol(create_ab_line_symbol())
        self.ab_line_layer.triggerRepaint()

        # Add to project and layer group (consistent with all other plugin layers)
        layer_group = get_layer_group(self.group_name)
        clean_layer_add(self.ab_line_layer)
        layer_group.addLayer(self.ab_line_layer)

        # Update plugin map canvas
        self.mapCanvas.setLayers(self.get_canvas_layers())
        self.mapCanvas.refresh()

        # Update main canvas
        if self.plugin_instance and self.plugin_instance.iface:
            self.plugin_instance.iface.layerTreeView().refreshLayerSymbology(self.ab_line_layer.id())
            self.plugin_instance.iface.mapCanvas().refresh()

    def display_blocks_on_map(self, blocks, crs):
        layer_group = get_layer_group(self.group_name)

        # Remove previous block layers before creating new ones
        if self.block_layers:
            old_ids = [bl.id() for bl in self.block_layers if is_layer_valid(bl)]
            if old_ids:
                QgsProject.instance().removeMapLayers(old_ids)
            self.block_layers = []

        block_layers = []

        for block in blocks:
            block_layer = QgsVectorLayer(
                f"Polygon?crs={crs.authid()}",
                block['label'],
                "memory"
            )
            
            provider = block_layer.dataProvider()
            block_layer.startEditing()
            
            for plot in block['plots']:
                feature = QgsFeature()
                feature.setGeometry(plot['geometry'])
                provider.addFeature(feature)
            
            block_layer.commitChanges()
            
            block_layer.renderer().setSymbol(create_block_symbol())
            block_layer.triggerRepaint()
            
            QgsProject.instance().addMapLayer(block_layer, False)
            layer_group.addLayer(block_layer)
            block_layers.append(block_layer)

        # Store reference so cleanup and get_canvas_layers can access them
        self.block_layers = block_layers

        if block_layers:
            self.mapCanvas.setDestinationCrs(crs)

            self.mapCanvas.setLayers(self.get_canvas_layers())
            
            # Zoom to field extent with padding instead of blocks
            if self.feld_layer:
                field_extent = self.feld_layer.extent()
                padding_x = field_extent.width() * FIELD_EXTENT_PADDING_FRACTION
                padding_y = field_extent.height() * FIELD_EXTENT_PADDING_FRACTION
                padded_extent = QgsRectangle(
                    field_extent.xMinimum() - padding_x,
                    field_extent.yMinimum() - padding_y,
                    field_extent.xMaximum() + padding_x,
                    field_extent.yMaximum() + padding_y
                )
                
                self.mapCanvas.setExtent(padded_extent)
                self.mapCanvas.refresh()
                
                if self.plugin_instance and self.plugin_instance.iface:
                    main_canvas = self.plugin_instance.iface.mapCanvas()
                    main_canvas.setDestinationCrs(crs)
                    main_canvas.setExtent(padded_extent)
                    main_canvas.refresh()
                    for layer in block_layers:
                        self.plugin_instance.iface.layerTreeView().refreshLayerSymbology(layer.id())

    def load_saved_params(self):
        """Load previously saved parameters from JSON, populate UI, and restore saved layers."""
        json_path = os.path.join(self.output_dir, "ofe_parameter.json")
        if not os.path.exists(json_path):
            return

        try:
            with open(json_path, "r", encoding="utf-8") as f:
                params = json.load(f)
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("Could not load saved parameters: %s", e)
            return

        # Block all interactive controls that have side-effect signals so that
        # programmatic value-setting during restore doesn't trigger headland
        # recreation, canvas resets, etc.
        _signal_widgets = [
            self.checkbox_vorgewende, self.checkbox_vorgewende_t3,
            self.num_vorgewende, self.num_vorgewende_t3,
            self.int_faktoren, self.int_wiederholungen,
        ]
        for w in _signal_widgets:
            w.blockSignals(True)

        try:
            # --- Tab 1 fields ---
            self.txt_fragestellung.setPlainText(params.get("fragestellung", ""))
            self.txt_faktor1.setText(params.get("faktor1", ""))
            self.txt_faktorstufen1.setText(params.get("faktorstufen1_raw", ""))

            n_faktoren = params.get("n_faktoren", 1)
            self.int_faktoren.setValue(n_faktoren)
            self.on_faktoren_changed(n_faktoren)
            if n_faktoren == 2:
                self.txt_faktor2.setText(params.get("faktor2", ""))
                self.txt_faktorstufen2.setText(params.get("faktorstufen2_raw", ""))

            self.int_wiederholungen.setValue(params.get("wiederholungen", 1))
            self.faktorstufen1 = params.get("faktorstufen", [])

            # Versuchstyp
            vt_name = params.get("versuchstyp", "STREIFEN")
            try:
                self.versuchstyp = Versuchstyp[vt_name]
            except KeyError:
                self.versuchstyp = Versuchstyp.STREIFEN

            # Type-specific spinbox/checkbox fields
            ohne_vorgewende = params.get("ohne_vorgewende", False)
            vorgewendebreite = params.get("vorgewendebreite", 0)
            if self.versuchstyp is Versuchstyp.KLEINPARZELLE:
                self.num_parzellenbreite_x.setValue(params.get("parzellenbreite", 0))
                self.num_parzellenbreite_y.setValue(params.get("parzellenlaenge", 0))
                self.int_anzahl_x.setValue(params.get("anzahl_x", 0))
                self.int_anzahl_y.setValue(params.get("anzahl_y", 0))
                self.num_gap_x.setValue(params.get("gap_x", 0))
                self.num_gap_y.setValue(params.get("gap_y", 0))
                self.num_vorgewende_t3.setValue(vorgewendebreite)
                self.checkbox_vorgewende_t3.setChecked(ohne_vorgewende)
            else:
                self.num_parzellenbreite.setValue(params.get("parzellenbreite", 0))
                self.num_vorgewende.setValue(vorgewendebreite)
                self.checkbox_vorgewende.setChecked(ohne_vorgewende)

            # Set headland instance vars directly (no signal needed)
            self.ohne_vorgewende = ohne_vorgewende
            self.vorgewendebreite = vorgewendebreite

            # --- Tab 4 core plot fields ---
            self.txt_prefix_t4.setText(params.get("core_prefix", "core_"))
            self.num_core_length_t4.setValue(float(params.get("core_length", 0)))
            self.num_core_width_t4.setValue(float(params.get("core_width", 0)))
            self.cmb_placement_t4.setCurrentIndex(int(params.get("core_placement", 0)))
        finally:
            for w in _signal_widgets:
                w.blockSignals(False)

        # --- Restore persisted layers ---
        layer_files = params.get("layer_files", {})
        if not layer_files:
            logger.info("Loaded saved parameters (no layer files) from %s", json_path)
            return

        layer_group = get_layer_group(self.group_name)

        def _load_layer(key, name, provider="ogr"):
            path = layer_files.get(key)
            if not path:
                logger.debug("load_saved_params: no path saved for '%s'", key)
                return None, False
            if not os.path.exists(path):
                logger.warning("load_saved_params: file missing for '%s': %s", key, path)
                return None, False
            # Reuse existing layer to preserve user-customised styling
            existing = next(
                (l for l in QgsProject.instance().mapLayers().values()
                 if l.source().split("|")[0] == path),
                None
            )
            if existing:
                logger.debug("load_saved_params: reused existing '%s' as '%s'", key, name)
                return existing, False
            layer = QgsVectorLayer(path, name, provider)
            if not layer.isValid():
                logger.warning("load_saved_params: layer invalid for '%s': %s", key, path)
                return None, False
            clean_layer_add(layer)
            layer_group.addLayer(layer)
            logger.debug("load_saved_params: loaded '%s' as '%s'", key, name)
            return layer, True

        # Restore combo box selections to original user-selected source layers
        def _restore_combo(layer_id, *combos):
            if not layer_id:
                return
            src = QgsProject.instance().mapLayer(layer_id)
            if src:
                for combo in combos:
                    combo.setLayer(src)

        _restore_combo(
            params.get("selected_feld_id"),
            self.mapLayerComboBox_Feldgrenze,
            self.mapLayerComboBox_Feldgrenze_t3,
        )
        _restore_combo(
            params.get("selected_lenkspur_id"),
            self.mapLayerComboBox_Lenkspur,
            self.mapLayerComboBox_Lenkspur_t3,
        )
        _restore_combo(
            params.get("selected_af_id"),
            self.mapLayerComboBox_AF,
            self.mapLayerComboBox_AF_t3,
        )

        # Field boundary (plugin-reprojected copy)
        feld, feld_new = _load_layer("feld_layer", params.get("feld_layer_name", "Feldgrenze"))
        if feld:
            if feld_new:
                feld.renderer().setSymbol(create_field_symbol())
            self.feld_layer = feld
            self.target_crs = feld.crs()
            self.mapCanvas.setDestinationCrs(self.target_crs)
            self._applied_feld_id = params.get("selected_feld_id", feld.id())

        # Guidance line
        lenkspur, _ = _load_layer("lenkspur_layer", params.get("lenkspur_layer_name", "Lenkspur"))
        if lenkspur:
            self.lenkspur_layer = lenkspur
            self._applied_lenkspur_id = params.get("selected_lenkspur_id", lenkspur.id())

        # Exclusion / obstacle area
        af, af_new = _load_layer("af_layer", params.get("af_layer_name", "Ausschlussfläche"))
        if af:
            if af_new:
                af.renderer().setSymbol(create_obstacle_symbol())
            self.af_layer = af
            self._applied_af_id = params.get("selected_af_id", af.id())

        # Inner area (headland)
        inner, inner_new = _load_layer("inner_layer", params.get("inner_layer_name", "Inner area"))
        if inner:
            if inner_new:
                inner.renderer().setSymbol(create_headland_inner_symbol())
            self.innerLayer = inner

        # Buffer / headland pattern
        buf, buf_new = _load_layer("buffer_layer", params.get("buffer_layer_name", "Headland"))
        if buf:
            if buf_new:
                buf.renderer().setSymbol(create_headland_pattern_symbol())
            self.bufferLayer = buf

        # Restore headland active state directly — no setChecked to avoid signal cascade
        if self.innerLayer and self.bufferLayer:
            self.buffer_is_active = True

        # AB line
        ab, ab_new = _load_layer("ab_line_layer", params.get("ab_line_layer_name", "AB Line"))
        if ab:
            if ab_new:
                ab.renderer().setSymbol(create_ab_line_symbol())
            self.ab_line_layer = ab
            # Restore maptool geometry state so plot creation/randomisation work
            pt_a_coords = params.get("ab_pt_a")
            pt_b_coords = params.get("ab_pt_b")
            if pt_a_coords and pt_b_coords:
                pt_a = QgsPointXY(pt_a_coords[0], pt_a_coords[1])
                pt_b = QgsPointXY(pt_b_coords[0], pt_b_coords[1])
                self.maptool.p0 = pt_a
                self.maptool.pt_A = pt_a
                self.maptool.pt_B = pt_b
                self.maptool.ab_line = QgsGeometry.fromPolylineXY([pt_a, pt_b])
                logger.debug("load_saved_params: restored maptool AB line A=%s B=%s", pt_a_coords, pt_b_coords)

        # Plot layer
        plot, plot_new = _load_layer("plot_layer", params.get("plot_layer_name", "Trial plots"))
        if plot:
            if plot_new:
                apply_categorized_variant_renderer(plot, list(self.faktorstufen1))
            self.plot_layer = plot

        # Core plot layers
        for entry in layer_files.get("core_plot_layers", []):
            path = entry.get("path")
            name = entry.get("name", "core_plots")
            if not path or not os.path.exists(path):
                logger.warning("load_saved_params: core plot file missing: %s", path)
                continue
            # Check if this file is already loaded in the project to avoid duplicates.
            already = next(
                (l for l in QgsProject.instance().mapLayers().values()
                 if l.source().split("|")[0] == path),
                None
            )
            if already:
                self.core_plot_layers.append(already)
                logger.debug("load_saved_params: reused existing core plot layer '%s'", name)
                continue
            cl = QgsVectorLayer(path, name, "ogr")
            if cl.isValid():
                apply_categorized_variant_renderer(cl, list(self.faktorstufen1))
                QgsProject.instance().addMapLayer(cl, False)
                self._insert_core_layer_in_group(layer_group, cl)
                self.core_plot_layers.append(cl)
                logger.debug("load_saved_params: restored core plot layer '%s'", name)
            else:
                logger.warning("load_saved_params: core plot layer invalid: %s", path)

        # Enable the correct planning tab
        if self.versuchstyp is Versuchstyp.KLEINPARZELLE:
            self.tabWidget.setTabEnabled(2, True)
            self.tabWidget.setCurrentIndex(2)
        else:
            self.tabWidget.setTabEnabled(1, True)
            self.tabWidget.setCurrentIndex(1)

        # Enable Core Plots tab if plots exist
        if self.plot_layer and self.ab_line_layer:
            self.tabWidget.setTabEnabled(3, True)
            self._preselect_t4_layers()
        elif self.core_plot_layers:
            self.tabWidget.setTabEnabled(3, True)
            self._preselect_t4_layers()

        # Update canvas directly — showEvent acts as secondary sync for edge cases
        canvas_layers = self.get_canvas_layers()
        if canvas_layers:
            self.mapCanvas.setLayers(canvas_layers)

        if self.feld_layer:
            field_extent = self.feld_layer.extent()
            padding_x = field_extent.width() * FIELD_EXTENT_PADDING_FRACTION
            padding_y = field_extent.height() * FIELD_EXTENT_PADDING_FRACTION
            self.mapCanvas.setExtent(QgsRectangle(
                field_extent.xMinimum() - padding_x,
                field_extent.yMinimum() - padding_y,
                field_extent.xMaximum() + padding_x,
                field_extent.yMaximum() + padding_y,
            ))

        self.mapCanvas.refresh()

        logger.info("Restored saved session from %s - %d canvas layers: %s",
                    json_path, len(canvas_layers), [l.name() for l in canvas_layers])

        if self.plugin_instance and self.plugin_instance.iface:
            self.plugin_instance.iface.mapCanvas().refresh()

    def read_parameters(self):
        self.parzellenbreite = self.num_parzellenbreite.value()
        self.parzellenlaenge = 0.0
        self.gap_x = 0
        self.gap_y = 0

        self.wdh = self.int_wiederholungen.value()        
        self.vorgewendebreite = self.num_vorgewende.value()
        self.ohne_vorgewende = self.checkbox_vorgewende.isChecked()
        self.faktor1 = self.txt_faktor1.text().strip()
        
        faktorstufen1 = self.txt_faktorstufen1.text().strip()
        stufen1 = [s.strip() for s in faktorstufen1.split(',')]
        
        n_faktoren = self.int_faktoren.value()
        
        if n_faktoren == 2:
            self.faktor2 = self.txt_faktor2.text().strip()
            faktorstufen2 = self.txt_faktorstufen2.text().strip()
            stufen2 = [s.strip() for s in faktorstufen2.split(',') if s.strip()]
            
            if len(stufen1) == 1:
                QtWidgets.QMessageBox.warning(
                    self, 
                    self.tr("Warnung: Nur 1 Faktorstufe"),
                    self.tr("Faktor 1 hat nur eine Stufe: '{level}'\n\n"
                            "Für mehrere Faktorstufen bitte kommagetrennt eingeben, z.B.: a, b, c").format(level=stufen1[0])
                )
            if len(stufen2) == 1:
                QtWidgets.QMessageBox.warning(
                    self, 
                    self.tr("Warnung: Nur 1 Faktorstufe"),
                    self.tr("Faktor 2 hat nur eine Stufe: '{level}'\n\n"
                            "Für mehrere Faktorstufen bitte kommagetrennt eingeben, z.B.: x, y, z").format(level=stufen2[0])
                )
            
            self.faktorstufen1 = []
            for s1 in stufen1:
                for s2 in stufen2:
                    self.faktorstufen1.append(f"{s1}_{s2}")
        else:
            self.faktorstufen1 = stufen1
            if len(stufen1) == 1:
                QtWidgets.QMessageBox.warning(
                    self, 
                    self.tr("Warnung: Nur 1 Variante"),
                    self.tr("Es wurde nur eine Variante gefunden: '{level}'\n\n"
                            "Für mehrere Varianten bitte kommagetrennt eingeben, z.B.: V1, V2, V3").format(level=stufen1[0])
                )
        
        self.anzahl_x = self.wdh * len(self.faktorstufen1)
        self.anzahl_y = 1  # strip trials only

        # Special handling for small-plot experiments
        if self.versuchstyp is Versuchstyp.KLEINPARZELLE:
            self.parzellenbreite = self.num_parzellenbreite_x.value()
            self.parzellenlaenge = self.num_parzellenbreite_y.value()
            self.anzahl_x=self.int_anzahl_x.value()
            self.anzahl_y=self.int_anzahl_y.value()
            self.vorgewendebreite = self.num_vorgewende_t3.value()
            self.ohne_vorgewende = self.checkbox_vorgewende_t3.isChecked()
            self.gap_x = self.num_gap_x.value()
            self.gap_y = self.num_gap_y.value()
            logger.debug("read_parameters - anzahl_y: %d", self.anzahl_y)
        

    def get_canvas_layers(self):
        layers = []
        for cl in self.core_plot_layers:
            if is_layer_valid(cl):
                layers.append(cl)
        for bl in self.block_layers:
            if is_layer_valid(bl):
                layers.append(bl)
        if is_layer_valid(self.plot_layer):
            layers.append(self.plot_layer)
        if is_layer_valid(self.ab_line_layer):
            layers.append(self.ab_line_layer)
        if is_layer_valid(self.lenkspur_layer):
            layers.append(self.lenkspur_layer)
        if is_layer_valid(self.af_layer):
            layers.append(self.af_layer)
        if is_layer_valid(self.innerLayer):
            layers.append(self.innerLayer)
        if is_layer_valid(self.bufferLayer):
            layers.append(self.bufferLayer)
        if is_layer_valid(self.feld_layer):
            layers.append(self.feld_layer)
        if is_layer_valid(self.osm_layer):
            layers.append(self.osm_layer)
        return layers


    # TODO 10: init functions
    
    def init_settings(self):
        # Determine project directory (saved project path or home as fallback)
        project_file = QgsProject.instance().fileName()
        if project_file:
            self.project_dir = os.path.dirname(project_file)
        else:
            self.project_dir = os.path.expanduser("~")
        self.output_dir = os.path.join(self.project_dir, "ofe_planung")
        os.makedirs(self.output_dir, exist_ok=True)
        
    
    def cancel(self):
        self.maptool.hide()
        self.mapCanvas.unsetMapTool(self.maptool)


    def start(self) -> bool:
        self.mapCanvas.setMapTool(self.maptool)
        self.maptool.init_rubber()
